version: "3.8"
services:
  app:
    image: node:18.2.0-bullseye-slim
    working_dir: /app
    volumes:
      - .:/app
  page:
    image: node:18.2.0-bullseye-slim
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./page:/app
